micronaut:
  application:
    name: orcl-db-sse
  server:
    port: 8081
langgraph:
  url: http://0.0.0.0:2024
datasources:
  default:
    db-type: oracle
    url: ${JDBC_URL}                # e.g. jdbc:oracle:thin:@//HOST:PORT/SERVICE
    username: ${DB_USER} 
    password: ${DB_PASSWORD}
    driverClassName: oracle.jdbc.OracleDriver
    maximumPoolSize: 10


    