micronaut:
  application:
    name: sse-listener
datasources:
  default:
    db-type: oracle
    url: {JDBC_URL}                # e.g. jdbc:oracle:thin:@//HOST:PORT/SERVICE
    username: {DB_USERNAME} 
    password: ${DB_PASSWORD}
    driverClassName: oracle.jdbc.OracleDriver
    maximumPoolSize: 10
